import type { Metadata } from "next";
import { StaticLink as Link } from "@/components/ui/StaticLink";
import { ButtonLink } from "@/components/ui/ButtonLink";
import { Icon } from "@/components/ui/Icon";
import { FinalCta } from "@/components/marketing/FinalCta";
import { PlatformIllustration } from "@/components/marketing/PlatformIllustration";
import { SectionHeading } from "@/components/marketing/SectionHeading";
import { SuiteCard } from "@/components/marketing/SuiteCard";
import { createMetadata } from "@/lib/seo/metadata";
import { industries, suites } from "@/content/site";

export const metadata:Metadata=createMetadata("Enterprise Business Operating Platform","Run your entire business from one connected platform with Bridge Dynamics.");
const challenges=[["Disconnected systems","Critical information sits across applications that do not share a common operational view."],["Spreadsheet operations","Manual files create rework, inconsistency and avoidable operational dependency."],["Email approvals","Important decisions become difficult to track, measure and govern."],["Manual reporting","Leadership spends too much time assembling reports and too little time acting on them."],["Fragmented information","Multiple versions of the truth limit accountability and planning."],["Departmental silos","Teams work independently when customers, projects, people and finance should be connected."]];
const outcomes=["Improved operational visibility","Faster decision-making","Stronger accountability","Streamlined approvals","Better project control","Improved governance","Connected business operations","Better executive insight"];

export default function Home(){return <>
<section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">Enterprise Business Operating Platform</p><h1>Run Your Entire Business From One Connected Platform</h1><p className="lead">Bridge Dynamics connects your people, projects, customers, finance, procurement, operations and compliance in one secure enterprise business platform designed for growing organisations.</p><div className="actions"><ButtonLink href="/request-demo">Request a Demonstration</ButtonLink><ButtonLink href="/platform" variant="secondary">Explore the Platform</ButtonLink></div><div className="trust-line" aria-label="Platform qualities"><span>Secure by design</span><span>Configurable operations</span><span>Built for enterprise growth</span></div></div><PlatformIllustration/></div></section>
<section className="section"><div className="container split"><SectionHeading eyebrow="The operational challenge" title="Growth should not create operational fragmentation">As organisations grow, disconnected tools make it harder to see what is happening, coordinate work and act with confidence.</SectionHeading><div className="challenge-list">{challenges.map(([title,text])=><article className="challenge" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section className="section section--soft"><div className="container"><SectionHeading eyebrow="One connected platform" title="Six suites. One operational foundation.">Give each team relevant capability while preserving shared controls, information and accountability across the organisation.</SectionHeading><div className="suite-grid">{suites.map((suite,index)=><SuiteCard key={suite.name} suite={suite} index={index} showCapabilities={false}/>)}</div></div></section>
<section className="section"><div className="container"><SectionHeading eyebrow="Business outcomes" title="Turn connected information into operational confidence">Bridge Dynamics helps leadership and operational teams move from fragmented activity to clear, coordinated execution.</SectionHeading><div className="outcome-grid">{outcomes.map((item,index)=><article className="outcome" key={item}><span>0{index+1}</span><h3>{item}</h3></article>)}</div></div></section>
<section className="section section--brand"><div className="container split"><div><p className="eyebrow eyebrow--light">Designed around how you operate</p><h2>One platform, configured for your organisation</h2><p className="lead">Bridge Dynamics adapts to established processes without requiring a separate software product for every workflow.</p></div><ul className="check-list">{["Configurable workflows","Approval processes","Role-based permissions","Business rules","Notifications","Custom fields and forms","Operational reports","Customer-specific extensions"].map(item=><li key={item}>{item}</li>)}</ul></div></section>
<section className="section"><div className="container"><SectionHeading eyebrow="Industry context matters" title="Built for organisations with complex operating requirements"/><div className="industry-list">{industries.map((industry,index)=><article className="industry-row" key={industry.name}><span>0{index+1}</span><h3>{industry.name}</h3><p>{industry.description}</p><Link className="text-link" href="/industries">Industry view <span aria-hidden="true">→</span></Link></article>)}</div></div></section>
<section className="section section--brand"><div className="container split"><div><p className="eyebrow eyebrow--light">Security and trust</p><h2>Controls that support responsible enterprise operations</h2><p>Security is designed into access, data separation, activity history and deployment—not treated as an afterthought.</p><ButtonLink href="/security" variant="light">Explore security</ButtonLink></div><div className="trust-grid">{["Role-based access","Tenant isolation","Audit capabilities","Secure deployment","Data protection","Operational resilience"].map(item=><article className="trust-item" key={item}><Icon name="check"/><h3>{item}</h3></article>)}</div></div></section><FinalCta/></>}
